name: Daily Market Scan500

on:
  schedule:
    # Runs at 21:13 UTC (5:13 PM EDT) Monday through Friday to avoid server congestion
    - cron: '13 21 * * 1-5'
  workflow_dispatch: # Allows you to run it manually from a button on GitHub

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Run Market Scan Script
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
        run: python market-scan500.py
